# Generated by Django 4.0.6 on 2022-08-14 10:15

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_options_user_address_user_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.PositiveIntegerField(blank=True, default=11, validators=[users.models.validator_age], verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile_phone',
            field=models.CharField(max_length=11, unique=True, verbose_name='Мобильный номер'),
        ),
    ]
