# Generated by Django 4.0.5 on 2022-08-21 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_options_user_address_user_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mobile_phone',
            field=models.CharField(max_length=11, unique=True, verbose_name='Мобильный номер'),
        ),
    ]
