# Generated by Django 4.0.6 on 2022-08-07 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('mainapp', '0001_initial'), ('mainapp', '0002_product_specification'), ('mainapp', '0003_product_status'), ('mainapp', '0004_product_old_price_alter_product_status')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='имя')),
                ('image', models.ImageField(blank=True, upload_to='products_images')),
                ('description', models.TextField(blank=True, verbose_name='описание продукта')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='цена продукта')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='колличество на складе')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.productcategory')),
                ('specification', models.TextField(blank=True, verbose_name='характеристика')),
                ('status', models.CharField(blank=True, choices=[(None, 'Выберите если требуется'), ('sale', 'Распродажа'), ('new', 'Новинка'), ('most', 'Популярно')], max_length=6)),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, verbose_name='старая цена продукта')),
            ],
        ),
    ]
